# Generated by Django 5.2.11 on 2026-02-11 00:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("status", models.CharField(choices=[("captured", "Captured")], default="captured", max_length=20)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("platform_fee_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payment_method", models.CharField(choices=[("pix", "PIX"), ("card", "CARD")], max_length=10)),
                ("installments", models.PositiveSmallIntegerField(default=1)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("recipient_id", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ledger_entries", to="billing.payment"
                    ),
                ),
            ],
            options={
                "db_table": "ledger_entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
