# Generated by Django 5.2.11 on 2026-02-11 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("idempotency", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="idempotencyrecord",
            name="status_code",
        ),
    ]
